spring.application.name=inventario

# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ferreteria_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Data2026*
#spring.datasource.password=T0d0L0Pued0EnCr1st0*
# Driver JDBC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
